channelfix/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import IndexView, ProfileView, AddPollView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^add/', AddPollView.as_view(), name='add_poll'),
    url(r'^p/', include('polls.urls')),
    url(r'^register/', include('registration.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^u/(?P<pk>\w+)/$', ProfileView.as_view(), name='profile')
]

polls/urls.py
from django.conf.urls import url
from django.views import generic
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultView.as_view(), name='results'),
    url(r'^(?P<pk>[0-9]+)/vote/$', views.VoteView.as_view(), name='vote'),
]

registration/urls.py
from django.conf.urls import url
from . import views

app_name = 'registration'
urlpatterns = [
    url(r'^signin/$', views.SignInView.as_view(), name='sign_in'),
    url(r'^signup/$', views.sign_up, name='sign_up'),
    url(r'^signout/$', views.sign_out, name='sign_out'),
]

polls/models.py
"""
Poll models
"""

import datetime

from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):
    """
    The poll question.
    """

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        """
        Admin feature. Lets you check whether the post was recently published
        """

        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    """
    The choice of a question
    """

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class UserVote(models.Model):
    """
    Checks if the user already voted the question
    """

    voter = models.ForeignKey(User, on_delete=models.CASCADE)
    voted_question = models.ForeignKey(Question, on_delete=models.CASCADE)

channelfix/views.py
"""
Main app views
"""

from django.utils import timezone
from django.views.generic.base import TemplateView
from django.views import View
from django.http import JsonResponse
from django.urls import reverse
from django.contrib.auth.models import User
from django.shortcuts import redirect, get_object_or_404

from polls.models import Question

class IndexView(TemplateView):
    """
    Lists all the polls
    """

    template_name = 'index.html'

    def get(self, request):
        """
        Lists all the poll questions
        """

        if not request.user.is_authenticated:
            return redirect('registration:sign_in')

        context = self.get_context_data()
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        """
        Fetches the data needed for a poll question
        """

        context = super(IndexView, self).get_context_data(**kwargs)
        context['questions'] = Question.objects.all().order_by('-pub_date')
        return context


class ProfileView(TemplateView):
    """
    Shows the user's polls
    """

    template_name = 'profile.html'

    def get(self, request, pk):
        """
        List the user's poll question
        """
        print(pk)
        context = self.get_context_data(pk)
        return self.render_to_response(context)

    def get_context_data(self, pk, **kwargs):
        """
        Fetches all data needed for every poll questions
        """

        context = super(ProfileView, self).get_context_data(**kwargs)
        user = get_object_or_404(User, username=pk)
        question = user.question_set.all().order_by('-pub_date')
        context = {
            'user': user,
            'questions': question
        }

        return context

class AddPollView(View):
    """
    Shows the add poll view
    """

    def post(self, request, *args, **kwargs):
        """
        Adds details of a poll question that a user inputs
        """

        counter = int(request.POST['counter'])
        content = request.POST['question']
        print(counter)
        if counter == 0:
            return JsonResponse({'status': 'failed'})

        question = Question(
            question_text=content,
            pub_date=timezone.now(),
            owner=request.user
        )
        question.save()

        for i in range(0, counter):
            choice = request.POST['choices[' + str(i) + ']']
            question.choice_set.create(choice_text=choice, votes=0)

        return JsonResponse({
            'status': 'success',
            'question': question.question_text,
            'question_results': reverse('polls:results', args=(question.pk,)),
            'question_vote': reverse('polls:detail', args=(question.pk,))
        })

polls/views.py
"""
Poll views
"""

from math import ceil
from django.views.generic.base import TemplateView
from django.views import View
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, JsonResponse
from django.utils import timezone

from .models import Question, Choice, UserVote


class DetailView(TemplateView):
    """
    Display the area where the user votes for a poll question
    """

    template_name = 'polls/detail.html'

    def get(self, request, pk):
        """
        Displays the detail view
        """

        context = self.get_context_data(request, pk)
        return self.render_to_response(context)

    def get_context_data(self, request, pk, **kwargs):
        """
        Fetches the necessary data to view a poll question
        """

        question = get_object_or_404(Question, pk=pk)
        user_voted = UserVote.objects.filter(
            voter=request.user, voted_question=question
        )
        context = super(DetailView, self).get_context_data(**kwargs)
        if user_voted.exists():
            context['already_voted'] = True
        context['question'] = question
        return context


class ResultView(TemplateView):
    """
    Shows the poll results view
    """

    template_name = 'polls/results.html'

    def get(self, request, pk):
        """
        Displays the results of a vote
        """

        context = self.get_context_data(pk)
        return self.render_to_response(context)

    def get_context_data(self, pk, **kwargs):
        """
        Fetches the necessary data to retrieve the results of a poll question
        """
        context = super(ResultView, self).get_context_data(**kwargs)

        # calculates the percentage of votes
        stats = []
        total_votes = 0
        question = get_object_or_404(Question, pk=pk)
        choices = question.choice_set.all()
        for choice in choices:
            total_votes += choice.votes

        for choice in choices:
            if total_votes == 0:
                stats.append(0)
            else:
                tmp = ceil((choice.votes/total_votes)*100)
                stats.append(tmp)

        zipped = zip(choices, stats)

        context = {
            'total': total_votes,
            'question': question,
            'choices': zipped,
        }

        return context


class VoteView(View):
    """
    Lets you vote on a chosen poll.
    """

    def post(self, request, pk):
        """
        Chooses a choice of the poll question a user inputted
        """

        question = get_object_or_404(Question, pk=pk)
        try:
            choice = question.choice_set.get(pk=request.POST['choice'])
        except(KeyError, Choice.DoesNotExist):
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': 'Select one.'
            })
        else:
            UserVote.objects.create(
                voter=request.user,
                voted_question=question
            )
            choice.votes += 1
            choice.save()
            return HttpResponseRedirect(
                reverse('polls:results', args=(question.id,))
            )

channelfix/templates/add_poll.html
{% extends 'list.html' %}

{% block addpoll %}
    <div class="card bg-light mb-2">
    <div class="card-body">
        <form action="{% url 'add_poll' %}" method="post" id="add_question">
            {% csrf_token %}
            <input class="form-control card-title" type="text" placeholder="What's on your mind, {{request.user.first_name}}?" name="poll_name" style="font-size:1.75rem" id="poll_name" required>
            <div class="choices"></div>
            <div class="float-right add-choice">
                <button type="button" class="btn btn-sm btn-outline-primary" id="add">Add choice</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

channelfix/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %} - Pollr</title>  
        {% include 'styles.html' %}
        {% include 'scripts.html' %}
        {% block style %}{% endblock %}
    </head>
    <body>
        <div class="container">
            {% block nav %}{% endblock %}
            <div class="row">
                <div class="col-lg col-sm-1"></div>
                <div class="col-lg-7 col-sm-10">
                    {% block content %}{% endblock %}
                    {% block list %}{% endblock %}
                </div>
                <div class="col-lg col-sm-1">
                    
                </div>
            </div>
        </div>
    </body>
</html>

channelfix/templates/index.html
{% extends "add_poll.html" %}

{% block title %}Home{% endblock %}

channelfix/templates/list.html
{% extends "navbar.html" %}
<!-- 
{% block script %}
    require(['js/polls']);
{% endblock %} -->

{% block list %}
    {% block user %}{% endblock %}
    <div>
        {% block home %}{% endblock %}
        <h1 class="bold-text">Polls</h1>
    </div>
    {% if request.user.is_authenticated %}
        {% block addpoll %}{% endblock %}
    {% endif %}
    {% if questions %}
        <div id="polls_list">
        {% for question in questions %}
            <div class="card bg-light mb-2">
                <div class="card-body">
                    <h3 class="card-title">
                    {{question.question_text}}
                    </h3>
                    <div class="btn-group float-right">
                        <a href="{% url 'polls:detail' question.id %}" class="btn btn-sm btn-outline-primary">Vote</a>
                        <a href="{% url 'polls:results' question.id %}" class="btn btn-sm btn-outline-primary">
                            Results
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <p>No polls.</p>
    {% endif %}
{% endblock %}

channelfix/templates/navbar.html
{% extends "base.html" %}
{% load static %}

{% block style %}
    <link rel="stylesheet/less" type="text/css" href="{% static 'css/style.less' %}">
{% endblock %}

{% block nav %}
<nav class="navbar navbar-expand-lg fixed-top">
    <div class="navbar-collapse">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        </ul>

        {% if request.user.is_authenticated %}
            <a href="{% url 'profile' request.user.username %}" 
                style="margin-right:10px; font-size:14px">{{request.user.first_name}}</a>
            <a href="{% url 'registration:sign_out' %}" class="btn btn-sm btn-primary float-right">Sign out</a>
        {% endif %}
    </div>
</nav>
{% endblock %}

channelfix/templates/profile.html
{% extends "list.html" %}

{% block title %}{{user.first_name}} {{user.last_name}}{% endblock %}

{% block home %}
<h6><a href="../../">← Polls</a></h6>
{% endblock %}

{% block user %} 
<h1 class="display-4 bold-text text-center">{{user.first_name}} {{user.last_name}}</h1>
<h2 class="text-muted font text-center">@{{user.username}}</h2>
<hr> 
{% endblock %}

channelfix/templates/scripts.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"  integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

<script src="{% static 'js/require.js' %}"></script>
<script src="{% static 'js/config.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

channelfix/templates/styles.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

polls/templates/polls/detail.html
{% extends "navbar.html" %}
{% block title %}{{question.question_text}}{% endblock %}

{% block content %}
    <h6><a href="../../">← Polls</a></h6>
    <h1 class="bold-text">Vote</h1>
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %} 
        <div class="card bg-light mb-3">
            <div class="card-body">
                <h2 class="card-title" style="margin-bottom:0px;">
                    {{question.question_text}}
                </h2>
            </div>
            {% if already_voted %}
                <div class="card-body" style="padding-top:0px">
                    <p class="card-text">You already voted.</p>
                </div>
                <div class="card-footer">
                    <a class="btn btn-sm btn-primary" href="{% url 'polls:results' question.id%}">View results</a>
                </div>
            {% else %}
                <ul class="list-group list-group-flush">
                    {% for choice in question.choice_set.all %}
                    <a href="#" class="list-group-item list-group-item-action">
                        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
                        <label for="choice{{ forloop.counter }}" style="margin-top:8px">
                            <b>{{ choice.choice_text }}</b>
                        </label>
                    </a>
                    {% endfor %}
                </ul>
                <div class="card-footer">
                    <input class="btn btn-sm btn-primary" type="submit" value="Submit vote">
                    <a class="btn btn-sm btn-link" href="{% url 'polls:results' question.id%}">View results</a>
                    <span style="padding-left:10px; color:red">
                        {% if error_message %}
                        <small>{{ error_message }}</small>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
        </div>
        <small class="card-text">Posted by 
            <a href="{% url 'profile' question.owner.username %}">
                <b>{{ question.owner.first_name }} {{question.owner.last_name}}</b>
            </a>
            <span class="text-muted">at {{ question.pub_date|date:'D M d, Y f A' }}</span>
        </small>
    </form>
{% endblock %}

polls/templates/polls/results.html
{% extends "navbar.html" %}
{% load static %}

{% block title %}{{question.question_text}} - Results{% endblock %}

{% block content %}
    <h6><a href="../">← Vote</a></h6>
    <h1 class="bold-text">Results</h1>
    <div class="card bg-light mb-3">
        <div class="card-body">
            <h2 class="card-title" style="margin-bottom:0px;">
                {{question.question_text}}
            </h2>
        </div>
        <ul class="list-group list-group-flush">
            {% for choice, percent in choices %}
                <li class="list-group-item">
                    <b>{{ choice.choice_text }}</b> 
                    <span class="float-right">{{ choice.votes }} vote{{ choice.votes|pluralize }}</span>
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: {{ percent }}%" ></div>
                    </div>
                </li>
            {% endfor %}
        </ul>
        <div class="card-footer">
            <a class="btn btn-sm btn-primary" href="{% url 'polls:detail' question.id%}">Vote</a>
            <span style="padding-left:10px">
                <small>{{ total }} vote{{ total|pluralize }}</small>
            </span>
        </div>
    </div>
    <small class="card-text">Posted by 
        <a href="{% url 'profile' question.owner.username %}">
            <b>{{ question.owner.first_name }} {{question.owner.last_name}}</b>
        </a>
        <span class="text-muted">at {{ question.pub_date|date:'D M d, Y f A' }}</span>
    </small>
{% endblock %}